### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_WRITE in windows _midia5_platform_send_data

### ISSUE THREAD

**Issue by connorjclark** [NewCreature/Allegro-Legacy#39]
I have a user crash report that lands in this method: https://zeldaclassic.sentry.io/share/issue/97684d22a3a146f1851588b9fd77e424/

It seems that `cm_data` is null here.

My expectation is that if `midia5_create_output_handle` failed (due to `_midia5_init_output_platform_data` not being able to get a MIDIA5_PLATFORM_DATA handle), then `a5_midi_init` (allegro5 midi init method) would fail and so `midi_driver->raw_midi` should be null now. Perhaps that's not the case?

The user that reported this crash was able to fix this by running something called [Codec Tweak Tool](https://codecguide.com/download_other.htm) (following this [guide](https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/it-looks-like-windows-just-forgot-how-to-play/c491f021-5ba6-4ea5-89af-1bc550e8d0f6?auth=1%20last%20post%20on%20this))

**Comment by NewCreature** [comment]
This looks like a bug in MIDIA5. When creating an output handle with `midia5_create_output_handle()`, the platform-specific code it defers to has the potential to return `NULL`. When this happens, `midia5_create_output_handle()` should fail and return `NULL` instead of the partially initialized handle.

**Comment by NewCreature** [comment]
Fixed in dc2d68ad51598d0d0c3b94b4cff905a409cc6ecf.
